### ISSUE TITLE
No devices show up in OBS

### ISSUE THREAD

**Issue by steviek926** [KillerBOSS2019/TP-GoveePlugin#2]
Hi there and thank you for the awesome plugins. when i downloaded your last govee plugin for obs. on restart, it asked for my api, i did it and it said account linked. when i try to have a action like change light color or turn light off and on, the devices box is blank and there is nothing to choose from. I'm using one H6001701-MG. The app on my ipad works so i know the light works. any suggestions?

**Comment by DamienStaebler** [comment]
Sorry for late response but I don't think that model support to communicate with API

**Comment by steviek926** [comment]
Yo bro you’re good. I got the 6003s to work with home assistant. Just cant get them to show up in touch portal

**Comment by DamienStaebler** [comment]
If is h6003 it should work with the plugin try
1. Is the H6003 connected to the Govee app?
2. If that didn't work can you upload the log file should be in `%appdata%/TouchPortal/plugins/TP-GoveePlugin/` before you upload look in the log remove the api key from the log and send it to me here
